module.exports = {
	parser: '@typescript-eslint/parser',
	parserOptions: {
		ecmaFeatures: {
			jsx: true,
		},
		ecmaVersion: 12,
		project: [
			'./tsconfig.json',
		],
		tsconfigRootDir: __dirname,
	},
	plugins: [
		'@typescript-eslint/eslint-plugin',
		'eslint-plugin-react',
		'eslint-plugin-tailwindcss',
		'import',
		'import-newlines',
		'perfectionist',
		'react-hooks',
		'simple-import-sort',
		'unused-imports',
	],
	extends: [
		'airbnb-base',
		'airbnb-typescript/base',
		'plugin:@typescript-eslint/recommended',
		'plugin:tailwindcss/recommended',
	],
	rules: {
		'@typescript-eslint/ban-ts-comment': 'off',
		'@typescript-eslint/consistent-type-exports': 'error',
		'@typescript-eslint/indent': [
			'error', 'tab',
			{
				SwitchCase: 1,
				ignoredNodes: [
					'FunctionExpression > .params[decorators.length > 0]',
					'FunctionExpression > .params > :matches(Decorator, :not(:first-child))',
					'ClassBody.body > PropertyDefinition[decorators.length > 0] > .key',
					'PropertyDefinition[decorators]',
					'TSUnionType',
					'TSTypeParameterInstantiation',
					'TSIntersectionType',
				],
			},
		],
		'@typescript-eslint/lines-between-class-members': 'off',
		'@typescript-eslint/no-empty-interface': 'off',
		'@typescript-eslint/no-explicit-any': 'off',
		'@typescript-eslint/no-non-null-assertion': 'off',
		'@typescript-eslint/no-shadow': 'off',
		'@typescript-eslint/no-unnecessary-type-constraint': 'off',
		'@typescript-eslint/no-use-before-define': 'off',
		'@typescript-eslint/no-var-requires': 'off',
		'arrow-body-style': 'off',
		'class-methods-use-this': 'off',
		'consistent-return': 'off',
		'global-require': 'off',
		'import-newlines/enforce': ['error', { items: 2, 'max-len': 160, semi: true }],
		'import/extensions': 'off',
		'import/no-extraneous-dependencies': 'off',
		'import/prefer-default-export': 'off',
		indent: 'off',
		'jsx-quotes': [2, 'prefer-double'],
		'max-classes-per-file': 'off',
		'max-len': ['error', { code: 200 }],
		'no-await-in-loop': 'off',
		'no-console': 'off',
		'no-continue': 'off',
		'no-extra-boolean-cast': 'off',
		'no-nested-ternary': 'off',
		'no-param-reassign': 'off',
		'no-plusplus': 'off',
		'no-restricted-globals': 'off',
		'no-restricted-syntax': 'off',
		'no-spaced-func': 'off',
		'no-tabs': 'off',
		'no-underscore-dangle': 'off',
		'object-curly-newline': [
			'error',
			{
				ObjectExpression: {
					consistent: true,
					multiline: true,
				},
				ObjectPattern: {
					consistent: true,
					multiline: true,
				},
				ImportDeclaration: {
					consistent: true,
					multiline: true,
					minProperties: 3,
				},
				ExportDeclaration: {
					consistent: true,
					multiline: true,
					minProperties: 3,
				},
			},
		],
		'object-curly-spacing': ['error', 'always'],
		'padded-blocks': 'off',
		'perfectionist/sort-exports': [
			'error',
			{
				type: 'natural',
				order: 'asc',
			},
		],
		'perfectionist/sort-named-exports': [
			'error',
			{
				type: 'natural',
				order: 'asc',
			},
		],
		'prefer-destructuring': 'off',
		'react-hooks/exhaustive-deps': 'warn',
		'react-hooks/rules-of-hooks': 'error',
		'react/jsx-curly-spacing': ['error', 'never'],
		'react/jsx-tag-spacing': ['error',
			{
				closingSlash: 'never',
				beforeSelfClosing: 'never',
				afterOpening: 'never',
				beforeClosing: 'allow',
			},
		],
		'simple-import-sort/imports': 'error',
		'tailwindcss/no-custom-classname': 'off',
		'unused-imports/no-unused-imports': 'error',
	},
};
